# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "01a3f8a07f88862a60c927791c5a176b"
name = "nge-testing"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
# Handled by: app/routes/webhooks.app.products-create.tsx
name = "products-create"
topics = [ "products/create" ]
uri = "/webhooks/app/products-create"

[[webhooks.subscriptions]]
# Handled by: app/routes/webhooks.app.products-update.tsx
name = "products-update"
topics = [ "products/update" ]
uri = "/webhooks/app/products-update"

[[webhooks.subscriptions]]
# Handled by: app/routes/webhooks.app.products-delete.tsx
name = "products-delete"
topics = [ "products/delete" ]
uri = "/webhooks/app/products-delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
