# This file stores configurations for your Shopify app.
name = "Next Generation Event subscription"
application_url = "https://www.app.example.com/"
embedded = true

# [START get-access-scopes]
[access_scopes]
scopes = "write_products"
# [END get-access-scopes]

# [START change-api-version]
[events]
api_version = "unstable"
# [END change-api-version]

[[events.subscription]]
handle = "my_product_events"

topic = "Product"
actions = ["update"]
triggers = ["product.variants.price"]

uri = "https://your-app.com/events"

[webhooks]
api_version = "2024-07"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
