# This file stores configurations for your Shopify app.
name = "Next Generation Event subscription"
application_url = "https://www.app.example.com/"
embedded = true

# [START get-access-scopes]
[access_scopes]
scopes = "write_products"
# [END get-access-scopes]

# [START change-api-version]
[events]
api_version = "unstable"
# [END change-api-version]

# [START subcribe-create-handle]
[[events.subscription]]
handle = "create_product_events"
# [END subcribe-create-handle]

# [START subcribe-create-topic-action]
topic = "Product"
actions = ["create"]
# [END subcribe-create-topic-action]

# [START subcribe-create-uri]
uri = "/nges/app/products-create"
# [END subcribe-create-uri]

# [START subcribe-delete]
[[events.subscription]]
handle = "delete_product_events"

topic = "Product"
actions = ["delete"]

uri = "/nges/app/products-delete"
# [END subcribe-delete]

# [START subcribe-update]
[[events.subscription]]
handle = "update_product_events"

topic = "Product"
actions = ["update"]
triggers = ["product.variants.price"]

uri = "/nges/app/products-update"
# [END subcribe-update]
