# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ddf198b354fc4fac96060c507e30d27b"
name = "react-router-app-proxy"
handle = "react-router-app-proxy"
application_url = ""
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_products"

[auth]
redirect_urls = [
  "/auth/callback",
  "/auth/shopify/callback",
  "/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "/a/proxy"
subpath = "proxy"
prefix = "a"
