name = "Events subscription"
application_url = "https://example.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

# [START events-access-scopes]
[access_scopes]
scopes = "read_products"
# [END events-access-scopes]

# [START events-version]
[events]
api_version = "unstable"
# [END events-version]

# [START events-create-configuration]
[[events.subscription]]
handle = "create_product_events"

topic = "Product"
actions = ["create"]

uri = "/events/app/products"
# [END events-create-configuration]

# [START events-delete-configuration]
[[events.subscription]]
handle = "delete_product_events"

topic = "Product"
actions = ["delete"]

uri = "/events/app/products"

# [END events-delete-configuration]

# [START events-update-configuration]
[[events.subscription]]
handle = "update_product_events"

topic = "Product"
actions = ["update"]
# [END events-update-configuration]

# [START events-update-triggers]
triggers = [
    "product.variants.price",
    "product.variants.compareAtPrice"
]
# [END events-update-triggers]

# [START events-update-uri]
uri = "/events/app/products"
# [END events-update-uri]

# [START events-update-query]
query = """
query price_change($productId: ID!, $variantsId: ID!){
  productVariant(id: $variantsId) {
    id
    price
    compareAtPrice
  }
  product(id: $productId) {
    id
    title
    status
  }
}
"""
# [END events-update-query]

# [START events-update-query-filter]
query_filter = "product.status:'ACTIVE'"
# [END events-update-query-filter]
