# This file stores configurations for your Shopify app.
name = "Example App"
client_id = "a61950a2cbd5f32876b0b55587ec7a27"
application_url = "https://www.app.example.com/"
embedded = true
handle = "example-app"

# [START get-access-scopes]
[access_scopes]
scopes = "write_products, read_orders"
# [END get-access-scopes]

# [START change-api-version]
[webhooks]
api_version = "2024-07"
# [END change-api-version]

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Webhooks can have filters
  # Only receive webhooks for product updates with a product price >= 10.00
  # See: https://shopify.dev/docs/apps/build/webhooks/customize/filters
  # [[webhooks.subscriptions]]
  # topics = ["products/update"]
  # uri = "/webhooks/products/update"
  # filter = "variants.price:>=10.00"

  # Mandatory compliance topic for public apps only
  # See: https://shopify.dev/docs/apps/build/privacy-law-compliance
  # [[webhooks.subscriptions]]
  # uri = "/webhooks/customers/data_request"
  # compliance_topics = ["customers/data_request"]

  # [[webhooks.subscriptions]]
  # uri = "/webhooks/customers/redact"
  # compliance_topics = ["customers/redact"]

  # [[webhooks.subscriptions]]
  # uri = "/webhooks/shop/redact"
  # compliance_topics = ["shop/redact"]

  # [START configure-subscription-pubsub]
  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "pubsub://<PROJECT-ID>:<PUBSUB-TOPIC-ID>"
  # [END configure-subscription-pubsub]

  # [START configure-subscription-https]
  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/app/orders-create"
  # [END configure-subscription-https]

  # [START configure-subscription-eventbridge]
  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "arn:aws:events:<AWS-REGION>::event-source/aws.partner/shopify.com/<APP-ID>/<EVENT-SOURCE-NAME>"
  # [END configure-subscription-eventbridge]